
const GENESIS_MISMATCH = 'GENESIS_MISMATCH';
const DEST_MISMATCH = 'DEST_MISMATCH';
const PAYLOAD_MISMATCH = 'PAYLOAD_MISMATCH';

module.exports = { GENESIS_MISMATCH, DEST_MISMATCH, PAYLOAD_MISMATCH }
