
const GENESIS_MISMATCH = 'GENESIS_MISMATCH';
const DEST_MISMATCH = 'DEST_MISMATCH';
const PAYLOAD_MISMATCH = 'PAYLOAD_MISMATCH';
const INP_MISMATCH = 'INP_MISMATCH';

const DEFAULT_TEST_GATEWAY = 'https://gateway-test1.unicity.network:443';
const DEFAULT_LOCAL_GATEWAY = 'http://localhost:8847';

module.exports = { GENESIS_MISMATCH, DEST_MISMATCH, PAYLOAD_MISMATCH, INP_MISMATCH, DEFAULT_LOCAL_GATEWAY, DEFAULT_TEST_GATEWAY }
